<div style="border:solid green 2px; padding: 20px">

<b>Привет, Наталья!</b>

Меня зовут Ярослав П. и я буду проверять твой проект. Попробую помочь сделать тебе его еще лучше!

Предлагаю общаться на «**ты**». Если это неприемлемо, обязательно напиши мне в комментариях — мы перейдем на «**вы**».

Ниже ты найдешь мои комментарии - пожалуйста, не перемещай, не изменяй и не удаляй их. Я буду использовать цветовую разметку:

<div class="alert alert-danger">
<b>Комментарий ревьюера:</b> Так выделены самые важные замечания. Без их отработки проект не будет принят. </div>

<div class="alert alert-warning">
<b>Комментарий ревьюера:</b> Так выделены небольшие замечания или советы.

</div>

<div class="alert alert-success">
<b>Комментарий ревьюера:</b> Так я выделяю все остальные комментарии.</div>

Давай работать над проектом в диалоге: если ты что-то меняешь в проекте или отвечаешь на мои комменатри — пиши об этом. Мне будет легче отследить изменения, если ты выделишь свои комментарии:
<div class="alert alert-info"> <b>Комментарий студента:</b> Например, вот так.</div>

Всё это поможет выполнить повторную проверку твоего проекта оперативнее. 
    
    
### <span style="color:orange">Обратная связь</span><a class="tocSkip">

- Проект хорошо выполнен и грамотно оформлен.
- Ответ на вопрос верный, однако здесь преполагается математическое обоснование. 
- Также предполагается немного другой способ шифрования - а именно умножение матрицы признаков на квадртаную обратимую рандомную матрицу.
    
### <span style="color:orange">Обратная связь (v2)</span><a class="tocSkip">

- Проект отлично доработан, спасибо за уделенное время!
    
Проект принят, успехов в дальнейшем обучении!

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера</b>

Отличное введение.

</div>


## Загрузка данных

In [1]:
import pandas as pd
import numpy as np


from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [2]:
df= pd.read_csv('/datasets/insurance.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
display(df.head())

print(df['Зарплата'].unique())

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

[49600. 38000. 21000. 41700. 26100. 41000. 39700. 38600. 49700. 51700.
 36600. 29300. 39500. 55000. 43700. 23300. 48900. 33200. 36900. 43500.
 36100. 26600. 48700. 40400. 38400. 34600. 34800. 36800. 42200. 46300.
 30300. 51000. 28100. 64800. 30400. 45300. 38300. 49500. 19400. 40200.
 31700. 69200. 33100. 31600. 34500. 38700. 39600. 42400. 34900. 30500.
 24200. 49900. 14300. 47000. 44800. 43800. 42700. 35400. 57200. 29600.
 37400. 48100. 33700. 61800. 39400. 15600. 52600. 37600. 52500. 32700.
 51600. 60900. 41800. 47400. 26500. 45900. 35700. 34300. 26700. 25700.
 33300. 31100. 31500. 42100. 37300. 42500. 27300. 46800. 33500. 44300.
 41600. 53900. 40100. 44600. 45000. 32000. 38200. 33000. 38500. 51800.
 33800. 46400. 43200. 31800. 50200. 35100. 30700. 45800. 49300. 42800.
 33600. 50300. 34000. 36400. 44900. 43600. 54600. 52800. 29700. 39000.
 44100. 31900. 37700. 35200. 43100. 51300. 47500. 40800. 26800. 64900.
 35900. 31200. 39900. 43300. 33900. 40700. 44700. 53400. 30600. 56000.
 35600

Столбец "Зарплата" у всех отображается как целочисленная сумма без дробной части, поэтому смело может перевести его целое число. 

Обработаем тип данных столбцов: Возраст, Зарплата. Переведем в тип int

In [5]:
df['Возраст'] = df['Возраст'].astype('int')
df['Зарплата'] = df['Зарплата'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null int64
Зарплата             5000 non-null int64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: int64(5)
memory usage: 195.4 KB


### Вывод

Функция info показало нам что 5 000 строк в датасете, столбцы не имеют пропущенных данных.
Возраст, зарплата переведены у удобных для обработки тип.


<div class="alert alert-block alert-success">
<b>Комментарий ревьюера</b>

Хороший первый взгляд на данные. Также в начале полезно провести небольшой анализ данных (несмотря на то, что проект небольшой и в целом это не требуется). Нет ли каких-либо аномальных значений, например, в возрасте, как распределен целевой признак.

</div>

## Умножение матриц

Определяем признаки и целевой признак.

- Признаки: пол, возраст и зарплата застрахованного, количество членов его семьи.

- Целевой признак: количество страховых выплат клиенту за последние 5 лет.

In [6]:
features = df.drop('Страховые выплаты',axis=1)
target = df['Страховые выплаты']

Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии?

================================

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

In [7]:
def MSE_w(features,target):
    X = np.concatenate((np.ones((features.shape[0], 1)), features), axis=1)
    y = target
    w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
    return 'Вектор весов линейной регрессии: ', w[1:]

In [8]:
def LR(features,target):
    model = LinearRegression()
    model.fit(features, target)
    predictions = model.predict(features)
    print('Коэффициент детерминации: ', r2_score(target, predictions))
    return 'Коэффициент признаков: ', model.coef_

In [9]:
MSE_w(features,target)

('Вектор весов линейной регрессии: ',
 array([ 7.92580563e-03,  3.57083050e-02, -1.70081903e-07, -1.35676627e-02]))

In [10]:
LR(features,target)

Коэффициент детерминации:  0.42494550308169177


('Коэффициент признаков: ',
 array([ 7.92580563e-03,  3.57083050e-02, -1.70081903e-07, -1.35676627e-02]))

**Вопрос** изменится ли качество линейной регрессии после умножения признаков на обратную матрицу?

**Ответ:**  не изменится

**Обоснование:**    $$
a = X_1 w
$$
$ a = X_1 (X^T X)^{-1} X^T y = X_1 X^{-1} (X^T)^{-1} X^T y = X_1 X^{-1} y $
$ a_1 = (X_1 A) ((X A)^T X A)^{-1} (X A)^T y =  (X_1 A) (X A)^{-1} ((X A)^T)^{-1} (X A)^T y = (X_1 A) A^{-1}X^{-1} (X^T)^{-1}(A^T)^{-1} A^T X^T y = X_1 A A^{-1} X^{-1} (X^T)^{-1}(A^T)^{-1} A^T X^T y = X_1 X^{-1} y $

Значение предсказания $a$ не меняется, если умножать матрицу признаков на обратимую матрицу.

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера</b>

Ответ верный!

</div>


<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера</b>

<s>Только здесь предполагается математическое обоснование :) Привожу формулы, которые тебе пригодятся.

<div  align='center'>
<p style='border: 2px solid black; padding: 15px; width: 30%' >
$$
(A \cdot B)^{-1} = B^{-1} \cdot A^{-1} \\
(A^T)^{-1} = (A^{-1})^T
$$
</p>
</div>
    
    
<div style='margin: 5px' align='center'>
<p style='border: 2px solid black; padding: 15px; width: 30%' >
$$
A \cdot (B \cdot C) = (A \cdot B) \cdot C \\
A \cdot B \neq B \cdot A \\
(A \cdot B)^T = B^T \cdot A^T \\
$$
</p>
</div>
    
Также есть одна частая ошибка. Так как матрицы $X$ и $X^T$, а также $(XP)^T$ и $XP$, прямогульные, то обратных матриц у них нет, то есть открывать скобки так нельзя:
    
$$
(X^T X)^{-1} \neq  X^{-1} \cdot (X^T)^{-1}
$$  
    
$$
((XP)^T(XP))^{-1} \neq (XP)^{-1}  \cdot ((XP)^T)^{-1}
$$

</div>


<div class="alert alert-info"> <b>Комментарий студента:</b> Привет! сделано</div>


<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера (v2)</b>

Все практически верно! Но так как матрицы $X$ и $X^T$, а также $(XP)^T$ и $XP$, прямогульные, то обратных матриц у них нет. Здесь правильный подход такой. То есть сначала открываем внутренние скобки, потом группируем в три квадратные матрицы, а потом раскрываем скобки:

$$
((XP)^T(XP))^{-1} = (P^T\cdot  X^T\cdot  X\cdot  P)^{-1} = (P^T\cdot (X^T  X)\cdot  P)^{-1} = P^{-1} \cdot (X^T  X)^{-1} \cdot (P^T)^{-1}
$$
    
Приведу полное доказательство:
    
1) Пусть новая матрица признаков:
$$
X_P = XP
$$

2) Тогда новый вектор весов будет выглядеть следующим образом:
$$
w_P = ((XP)^T XP)^{-1} (XP)^T y = (P^T X^T XP)^{-1} P^T X^T y = (P^T\cdot (X^T  X)\cdot  P)^{-1} P^T X^T y = P^{-1} \cdot (X^T  X)^{-1} \cdot (P^T)^{-1}  P^T X^T y =
$$
$$
= P^{-1} \cdot (X^T  X)^{-1} \cdot E \cdot X^T y = P^{-1} \cdot (X^T  X)^{-1} \cdot  X^T y
$$
<br>
3) Заметим, что в текущей формуле можно выявить формулу обучения ($w$). 
$$
w = (X^T X)^{-1} X^T y
$$
<br>
Преобразуем.
$$
w_P = P^{-1} w
$$

4) Построим предсказания по формуле для новой матрицы признаков и вектора весов
$$
a_P = X_P w_P = X P P^{-1} w = XEw = Xw
$$

То есть
    
$$
a_P = a
$$
    
</div>


## Алгоритм преобразования

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера</b>

Способ интересный, однако в рамках данного задание предполагается немного другой способ шифрования :)

1. Создадим...
2. Проверим...
3. Умножим... и т.д.

</div>

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера</b>

<s>Пожалуйста, обрати внимание, что нам нужно умножить матрицу признаков на квадратную обратимую матрицу. Также не забудь проверить матрицу на обратимость после генерации, чтобы мы могли в дальнейшем расшифровать наши данные.

</div>


**Обоснование**
Этапы алгоритма:

- Составление матрицы $Y$.
- Проверка матрицы на обратимость. Вычисление детерминанта матрицы $Y$.
- Получение матрицы преобразованных признаков $Z = XY$.
- Применение алгоритма на преобразованных признаках $Z$.

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера (v2)</b>

👍

</div>


## Проверка алгоритма

Подготовим функции для работы

In [11]:
def LRMatrix(features_train, features_test, target_train, target_test):
    model = LinearRegression()
    model.fit(features_train, target_train)
    predictions = model.predict(features_test)
    print('Коэффициент детерминации: ', r2_score(target_test, predictions))
    return 'Коэффициент признаков: ', model.coef_

In [12]:
def LRMatrixStandart(features_train, features_test, target_train, target_test):
    model = LinearRegression()
    scaller = StandardScaler()
    pipeline = Pipeline([("standard_scaller", scaller),("linear_regression", model)])
    pipeline.fit(features_train, target_train)
    predictions = pipeline.predict(features_test)
    print('Коэффициент детерминации: ', r2_score(target_test, predictions))

Создаем тестовую и обучающую выборку данных

In [13]:
features_train, features_test, target_train, target_test = train_test_split(
    features, target, test_size=0.25, random_state=12345)

Расчитаем Коэффициент детерминации и Коэффициент признаков

In [14]:
LRMatrix(features_train, features_test, target_train, target_test)

Коэффициент детерминации:  0.4352275684083349


('Коэффициент признаков: ',
 array([ 1.79258370e-02,  3.57228278e-02, -5.46002729e-07, -1.26186599e-02]))

In [15]:
LRMatrixStandart(features_train, features_test, target_train, target_test)

Коэффициент детерминации:  0.43522756840833376


Модель ведет себя одинаково. Коэффициент детерминации в обоих  после обучения LinearRegression и StandardScaler одинаковы.

Создадим функцию преобразования матрицы

In [16]:
def convert(features):
    crypted_features = features
    n = features.shape[1]
    np.random.seed(12345)
    cipher_matrix = np.random.randint(1, 10, (n,n))
    det = np.linalg.det(cipher_matrix)
    while det == 0:
        np.random.seed(12345)
        cipher_matrix = np.random.randint(1, 10, (n,n))
        det = np.linalg.det(cipher_matrix)
    crypted_features = crypted_features @ cipher_matrix
    return crypted_features, cipher_matrix

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера (v2)</b>

Отлично, проверка на обратимость есть! Молодец, что реализовала автоматическую проверку на обратимость.

</div>


In [17]:
display(features.head())
features, convert_matrix = convert(features)
display(features.head())
convert_matrix

Пол  Возраст  Зарплата  Члены семьи
0    1       41     49600            1
1    0       46     38000            1
2    0       29     21000            0
3    0       21     41700            2
4    1       28     26100            0

0       1       2      3
0  99452  396931  347287  49899
1  76279  304140  266095  38329
2  42174  168087  147058  21203
3  83532  333667  291948  41861
4  52371  208890  182758  26301

array([[3, 6, 2, 5],
       [6, 3, 2, 7],
       [2, 8, 7, 1],
       [3, 2, 3, 7]])

Разобьем данные на тренировочную и обучающую выборку и проверим R2 значение уже на преобразованной матрице

In [18]:
features_train, features_test, target_train, target_test = train_test_split(
    features, target, test_size=0.25, random_state=12345)

In [19]:
LRMatrix(features_train, features_test, target_train, target_test)

Коэффициент детерминации:  0.4352275684083574


('Коэффициент признаков: ',
 array([ 0.01280453,  0.00328449, -0.00664342, -0.00538157]))

In [20]:
LRMatrixStandart(features_train, features_test, target_train, target_test)

Коэффициент детерминации:  0.4352275684083631


### Вывод

Качество линейной регрессии никак не поменялось. Данные  удалось зашифровать.

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера (v2)</b>

Результат подтвержден как математически, так и экспериментально, здорово.

</div>


## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [ ]  Весь код выполняется без ошибок
- [ ]  Ячейки с кодом расположены в порядке исполнения
- [ ]  Выполнен шаг 1: данные загружены
- [ ]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [ ]  Указан правильный вариант ответа
    - [ ]  Вариант обоснован
- [ ]  Выполнен шаг 3: предложен алгоритм преобразования
    - [ ]  Алгоритм описан
    - [ ]  Алгоритм обоснован
- [ ]  Выполнен шаг 4: алгоритм проверен
    - [ ]  Алгоритм реализован
    - [ ]  Проведено сравнение качества моделей до и после преобразования